<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logitech-BCC950-PTZ-Lib\PTZDevice.csproj" />
    <Reference Include="DirectShowLib-2005">
      <HintPath>..\Logitech-BCC950-PTZ-Lib\lib\DirectShowLib-2005.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
